### PR TITLE
Fixed N2 connections toolbar show/hide buttons

### LINKED ISSUE #1879: N2 Connections toolbar buttons don’t work
### Summary of Issue

The N2 toolbar connections buttons don't have tooltips and also don't cause any changes in the N2.

### Issue Type

- [X] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Example

The issue can be seen in the N2s on the docs, including https://openmdao.org/twodocs/versions/latest/features/model_visualization/n2_details.html

### Environment

N/A

### PR DESCRIPTION
**Pull request by tadkollar**
### Summary

The code for the toolbar connections buttons was accidentally removed when the hide solvers button was added. This fix restores it and adds a test for the buttons.

The positioning of the model height slider was also fixed (the slider button had been offset downwards).

### Related Issues

- Resolves #1879

### Backwards incompatibilities

None

### New Dependencies

None

### CODE REVIEW

File: openmdao/visualization/n2_viewer/src/N2Toolbar.js [hunk 1]
```diff
@@ -261,6 +261,27 @@ class N2Toolbar {
...
             });
 
+        new N2ToolbarButtonClick('#hide-connections', tooltipBox,
+            "Remove all connection arrows",
+            function (target) {
+                n2ui.n2Diag.clearArrows();
+                self._setRootButton(target);
+            });
+
+        new N2ToolbarButtonClick('#hide-connections-2', tooltipBox,
```
Comment (Kenneth-T-Moore) [inline openmdao/visualization/n2_viewer/src/N2Toolbar.js:271]: Why are there 2 hide-connections ("hide-connections" and "hide-connections-s")?

**Review by Kenneth-T-Moore — CHANGES_REQUESTED** [review]

File: openmdao/visualization/n2_viewer/src/N2Toolbar.js (hunk 1 above)
Comment (tadkollar) [reply openmdao/visualization/n2_viewer/src/N2Toolbar.js:271]: For toolbar buttons with pullouts, the "primary" button is replaced when a different pullout selection is clicked. E.g., if I hover over the connections button, the pullout appears, and if I click the "Show all connections in view" icon, that button replaces the "hide connections" one at the far left. The icon a button starts with is the same as one of the pullout selections, so they're differentiated by using different ids. 

I just noticed that the tooltip for that button was "Remove all connection arrows" regardless of the whether the button function was hide or show, so I made an update to fix that.

Comment (Kenneth-T-Moore) [reply openmdao/visualization/n2_viewer/src/N2Toolbar.js:271]: Thanks, that clears up my confusion.

**Review by Kenneth-T-Moore — APPROVED** [review]

**Review by swryan — APPROVED** [review]
